name:                aoc
version:             0.1.0.0
github:              "githubuser/aoc"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aoc#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- transformers
- fgl
- MemoTrie

ghc-options:
# - -Wall
# - -Wcompat
# - -O3
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
# - -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

_day: &day
  source-dirs: app
  other-modules: []
  dependencies: [aoc]


executables:
  aoc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    other-modules: []
    dependencies:
    - aoc

  d3:
    <<: *day
    main: d3.hs
  d4:
    <<: *day
    main: d4.hs
  d5:
    <<: *day
    main: d5.hs
  d6:
    <<: *day
    main: d6.hs
  d7:
    <<: *day
    main: d7.hs
  d8:
    <<: *day
    main: d8.hs
  d9:
    <<: *day
    main: d9.hs
  d10:
    <<: *day
    main: d10.hs
  d11:
    <<: *day
    main: d11.hs
  d12:
    <<: *day
    main: d12.hs
  d13:
    <<: *day
    main: d13.hs
  d14:
    <<: *day
    main: d14.hs
  d15:
    <<: *day
    main: d15.hs
  d16:
    <<: *day
    main: d16.hs
  d17:
    <<: *day
    main: d17.hs
  d18:
    <<: *day
    main: d18.hs


tests:
  aoc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc
