import GHC.Conc
import Control.Applicative
import System.IO.Unsafe

x = unsafePerformIO $ newTVarIO (0 :: Rational)

vbfg = pure 2
dwgb = pure 3
ctlr = pure 3
rzwt = liftA2 (+) fdqz hpqd
qwlr = pure 3
hgbz = pure 2
mbqp = liftA2 (+) cfmj gqrj
tmrn = pure 3
hbvn = liftA2 (*) rnrm brjj
pjjr = liftA2 (+) bvpg tfqn
fdnr = pure 10
vgcz = liftA2 (*) jngf mgzw
zzvb = pure 2
cgnn = pure 5
jqqq = liftA2 (*) fmvt vhzd
wlgc = pure 3
qmjl = pure 2
pjsd = liftA2 (*) gzgp vnsp
vtsq = liftA2 (/) hctt lmqf
blgq = pure 1
nrch = pure 13
lvjf = liftA2 (*) tjzh ffsc
jczs = pure 5
rfrs = pure 3
vjwh = liftA2 (*) mwdw bhnw
wpvc = liftA2 (*) jlzw mfvr
rgbh = pure 2
htzb = liftA2 (+) mttr mqmv
bwbl = liftA2 (*) pmhf lfsd
zfdj = pure 1
pjzf = liftA2 (*) tppt ftnh
wzfg = liftA2 (*) hhjv dlph
lddf = liftA2 (/) qjnr ffvl
jtfj = pure 17
vqhs = pure 5
tlrl = pure 4
httg = liftA2 (*) hhjb zhzb
dbrq = liftA2 (*) hfgs qlwz
qgjz = liftA2 (*) hqmg jchz
jfbw = pure 2
swmc = liftA2 (+) rldn cdgs
jpms = pure 2
jmmr = pure 5
lfjw = liftA2 (+) qngl tbhl
lstl = pure 5
gfrz = pure 2
hldd = pure 11
mdrm = pure 19
bnqb = pure 8
stbv = liftA2 (+) dwsv bvhp
glwg = liftA2 (+) jpzc djqc
qdcm = liftA2 (+) lgsd fjwr
sfgh = pure 2
bdsr = liftA2 (-) phdn gpmn
hldm = liftA2 (*) mjsp djsm
wlqt = pure 6
rftc = liftA2 (*) twcq fgnd
qrcn = liftA2 (+) rntw gcdg
nntn = pure 2
vljq = liftA2 (*) bbnn gprr
mstq = pure 2
rbhz = liftA2 (+) schl jwtq
mdwj = liftA2 (+) zhbj qrfp
cfgp = liftA2 (-) pnhq zfdj
nwnh = pure 7
dvgv = pure 2
wmrl = liftA2 (+) wjrw llvf
ldzp = liftA2 (+) mlwd mqcz
cnvf = liftA2 (/) jqfj nmdl
qqbg = liftA2 (+) njsw dvnc
mzmm = pure 3
ncwm = pure 2
wrmh = liftA2 (/) dprw jjsd
qrht = liftA2 (*) zprs jsqg
znlm = liftA2 (*) cmgv lqpm
jlsn = pure 6
fjfv = liftA2 (+) ljql fppt
ffjf = pure 5
gzsp = pure 5
ptrh = pure 13
vfsw = liftA2 (+) dvvp gjvc
slgm = pure 3
lpcg = liftA2 (+) dsnq btnn
rhlb = liftA2 (+) zhrc jcjv
chfc = pure 10
dptd = pure 2
mlhh = liftA2 (/) cpwr nbsf
sfqb = pure 2
zvtn = liftA2 (*) cbsp zwsm
bbcc = liftA2 (+) tmtp prfm
jwwb = liftA2 (*) nfdz zhdj
zhdt = liftA2 (+) jdfz fhpp
sdwq = pure 3
pwcz = liftA2 (*) vmgn gwlt
lfcz = pure 2
pzfh = liftA2 (/) hjmt zpfg
hctt = liftA2 (*) nfwb wgrs
msgl = pure 6
lqlw = liftA2 (+) vnfc qlwn
lddp = liftA2 (*) mchv htwg
zrtc = liftA2 (+) pwjc nrpb
nsmp = pure 2
nrwj = pure 2
rhhp = liftA2 (+) cnvf rjrf
lltr = liftA2 (+) qbzq jszc
qrfp = pure 4
fbtv = liftA2 (+) nvql fsrg
nhqr = pure 3
hghw = liftA2 (/) pmsr mmsw
wldw = pure 3
hfvw = liftA2 (+) vqjf wfgc
cmpc = pure 2
wrst = pure 2
ntzz = pure 5
ccvh = pure 2
fftf = liftA2 (+) gfpp cfmn
sfcf = liftA2 (-) vtsq dzwb
pltq = pure 3
lljs = pure 2
pqfd = pure 3
wtbg = pure 5
mhpf = pure 3
mccg = liftA2 (*) wbhc grrr
mfrl = liftA2 (/) zcvd chld
rnfh = liftA2 (*) wqgg dfrr
fscc = pure 4
sfrv = pure 7
frtg = pure 2
hnmn = pure 3
hhzv = pure 2
rstc = liftA2 (*) rwwl ftjl
qtdr = liftA2 (+) vnch ntbv
jmcf = pure 5
mgsh = liftA2 (*) tmbg lswz
rqsh = pure 11
blmh = liftA2 (-) tbhz vhbg
vwgj = liftA2 (*) nzvn gfrz
qclt = liftA2 (/) nnvb cmpc
jhrh = pure 3
lbqs = pure 4
zbwc = liftA2 (+) ntsp rnfh
ndvz = liftA2 (+) zsfr ftzh
rwdr = liftA2 (*) fdpq pccw
qzlq = liftA2 (-) gfbc vtnb
hwfd = liftA2 (/) ftmf gjdb
hcfd = pure 17
hbdp = pure 3
vzhw = liftA2 (*) nhqw tmlc
gpzt = liftA2 (+) lglv hldd
dtns = pure 8
ttbq = pure 3
cnnw = liftA2 (+) hdnh bhlv
vmcn = pure 4
ddgb = pure 3
cdrj = pure 4
jqfl = pure 2
lnfg = pure 4
hcgp = pure 6
pfjs = pure 3
frdt = liftA2 (+) bhfn vqdw
mpgn = pure 3
hgvp = pure 2
przl = pure 5
ptqz = pure 2
zzvh = liftA2 (*) qntv cbsb
gfdw = liftA2 (*) ctlm rctr
nhsd = pure 3
nrld = liftA2 (*) rjww wsns
bjng = liftA2 (*) gldg zpcv
crwm = liftA2 (+) jttb bwbl
cdnl = liftA2 (/) hjwh hgrg
mjvl = pure 2
mhjs = liftA2 (/) lcqf drlq
sglg = pure 3
hchl = liftA2 (/) wbzs wjwc
nnwg = pure 8
hghd = liftA2 (*) rwdw cmmf
lnlh = liftA2 (*) mddj vrzs
sjpp = liftA2 (+) dwlz qnwt
hdcw = liftA2 (*) vszc cgzl
hlbd = liftA2 (+) qrht lnlh
lzlg = liftA2 (*) vmpw bvqq
thlv = liftA2 (*) clnz qvcb
hlnl = pure 2
tjwc = pure 3
fzmp = liftA2 (/) htvj fszn
fvfj = pure 2
wphb = liftA2 (*) hlcj mwcc
qtgr = pure 2
bjvp = liftA2 (*) fsjv zsjb
gfvf = pure 5
chjr = liftA2 (*) nntt gplc
hwls = liftA2 (*) rsgc slwr
rmcv = pure 14
lrhw = pure 3
pnhq = liftA2 (+) ljts gbhr
lwqq = liftA2 (*) bccm wjlz
cqlp = liftA2 (+) cgjf gfvf
nfgv = liftA2 (*) hwcq qvdd
prlb = pure 12
tdcr = liftA2 (+) zbdn tfzl
spbs = liftA2 (+) fbtv zcvh
dfnv = pure 1
tmjj = pure 7
mjsp = liftA2 (*) tbtc hdqf
hbjl = liftA2 (*) glqm crss
dbfs = pure 2
jfqs = pure 3
spww = liftA2 (*) zppb mrmc
msvh = liftA2 (+) tfmq hrzl
rbvb = liftA2 (*) ljnn pftv
lzpw = liftA2 (+) clll slzl
tfcs = pure 4
bgwg = pure 3
mgpj = liftA2 (+) pnwt pbrt
zhrh = liftA2 (*) fcvq rnwn
zlwg = pure 9
ncgt = pure 3
hvlv = pure 2
gcdg = liftA2 (-) hnwb zbmj
tpww = pure 5
qsqw = liftA2 (*) wldw zlhb
lfdm = pure 3
bbtq = pure 2
ghch = pure 2
bjqp = liftA2 (*) ssgw nchg
qzrv = liftA2 (+) pcdv mwzc
mbgb = liftA2 (+) mhvg drft
gzbc = pure 5
ncrd = liftA2 (*) qqwf phjw
hpzf = pure 2
rntw = liftA2 (/) cnzm nrpt
tllp = pure 2
wrff = liftA2 (-) vjmp zpfh
llcq = pure 14
lfdd = pure 5
blcm = liftA2 (*) rjzv phrq
htbc = pure 13
hqnl = pure 5
mbjt = pure 2
mldp = pure 12
lgnh = liftA2 (-) rbvd gvrm
cfmg = pure 10
fgsd = pure 2
sgws = liftA2 (*) zwcl tqrl
lgcw = pure 20
cmzt = liftA2 (*) fmvz zjlh
fssb = liftA2 (*) bgcs rrvs
ntzh = pure 2
rfpp = pure 2
jgfg = pure 2
ppvj = pure 4
bcvc = liftA2 (+) gtpb wjvz
spfg = pure 4
csvr = liftA2 (/) hlbd vrqz
rphf = pure 2
hdnh = pure 16
fjwr = liftA2 (*) fjvf nwlt
hlqg = liftA2 (+) ccmz hzfj
hpdp = liftA2 (+) qlhd jwwb
hmgd = pure 5
zbdh = liftA2 (*) rmvv bggc
hpcn = liftA2 (+) cdnl zltq
dnhd = liftA2 (*) vjbn bhtd
mlnf = pure 12
hnzz = pure 20
zlsq = liftA2 (*) mhpf htnm
jqcj = pure 4
mlct = pure 5
nzmv = liftA2 (*) bttg vshr
jwdq = liftA2 (*) zhzl hsgn
crww = pure 3
lzcp = liftA2 (*) dhtg pltq
hggn = pure 2
qdfs = pure 3
rqlv = liftA2 (+) sfss mqpr
lbcq = liftA2 (*) drrb gvld
jqtj = pure 3
fsqs = pure 5
wjrw = liftA2 (*) jzps ptjz
lgpw = liftA2 (*) jjcq fgfg
rzzz = pure 15
fmwb = pure 19
mmtb = pure 3
cgfp = pure 2
chmm = pure 3
ljgz = liftA2 (+) csvr lppw
vqfq = liftA2 (+) hfhc ngml
ldmt = pure 4
zhhm = pure 9
fzpt = pure 3
ssdr = pure 13
fwnf = liftA2 (*) pjpr gtvw
bbqf = liftA2 (-) bjng msgl
bbjt = pure 7
fdpp = pure 14
nntt = pure 2
dpst = pure 2
gnmt = pure 15
wngv = pure 4
vzjm = liftA2 (*) jdzc cwtn
jfpl = liftA2 (+) njls gdgj
cqfh = liftA2 (+) vcmt qglp
dzwb = pure 2
mvwr = liftA2 (+) hbml dbsd
zsbm = liftA2 (*) qnsj mwjn
lfqf = pure 2
vqdw = liftA2 (+) zrwd hppn
rrvs = pure 10
rsbb = pure 2
crzd = liftA2 (-) flnb pshd
cgzl = pure 2
zvrn = liftA2 (+) mvzw wmrl
ftmf = liftA2 (-) wzcw vssf
pjpr = pure 5
hswl = liftA2 (/) gczz nnth
vnww = pure 5
dbsd = pure 3
tghv = liftA2 (*) zgsm hcfm
ttzb = liftA2 (+) phzt ntnq
ppmn = liftA2 (*) hrwm rjhr
ndmn = pure 5
zhvq = liftA2 (-) mgfs bnfw
zqfw = pure 3
hwmd = pure 7
hlmh = pure 3
ndlp = pure 13
vbgt = pure 14
vqsz = liftA2 (*) ccpw wqsm
ldsz = pure 3
wdqs = pure 1
zwsm = pure 4
ldfp = liftA2 (+) lzcp nfgv
ffdv = liftA2 (+) gwqq wpqr
crmv = pure 2
fwlf = liftA2 (/) hfcg jsbq
dqvm = liftA2 (/) bvbt nrvs
qwhg = liftA2 (/) hnng tdrs
rnqm = liftA2 (+) btjz zvfv
rhqg = liftA2 (+) nzzq sbqt
vwmm = liftA2 (*) mrwm zdbn
zbfs = pure 2
thnm = liftA2 (*) swtb whdm
qvpm = liftA2 (*) bcvh hnjc
pjdr = pure 2
qvzl = pure 5
ppjb = pure 2
cmbj = liftA2 (+) ccpc qfpd
hhjb = pure 2
wpcs = liftA2 (*) jswt zcnh
jqhd = liftA2 (+) pmvv jdvv
nsln = pure 3
fshs = pure 5
vrpw = pure 2
sqgq = pure 7
pmhf = liftA2 (+) rhln frbr
hcrj = liftA2 (-) jwhp jnwm
mswg = liftA2 (+) hrcv fqlc
gtnp = liftA2 (*) hvpg qsfc
vsbz = liftA2 (+) ljfn sjpp
ssqs = pure 2
lqqg = pure 4
bhlv = liftA2 (*) gtmz sjlw
lnvg = liftA2 (*) rldv fhmj
rwwl = liftA2 (*) gslb svzn
fmql = liftA2 (+) vwfn bzcd
tnqc = liftA2 (*) chbz nrbv
cqhd = liftA2 (/) gdvb swsc
vgqb = liftA2 (-) wnfn wldl
vhbg = pure 5
pmcp = pure 13
pflz = liftA2 (*) tjnh wcwl
dvnp = liftA2 (*) lqzn jmdr
lsgf = liftA2 (+) vpmd tggg
sszs = liftA2 (*) ndhf jncv
qqnq = liftA2 (*) gmnc gmbp
lcmt = liftA2 (+) cdrj gdmt
wsmp = liftA2 (*) fstv zvrn
rhvw = liftA2 (*) psbw lfgf
htdr = liftA2 (-) spbs pdrt
mtrz = liftA2 (*) rmjp glfz
mzvv = liftA2 (+) hzbh qmjl
pmvv = liftA2 (/) mljh dwfs
bjnm = liftA2 (+) fdsj dwlf
jjrr = pure 19
dqch = pure 2
rmnr = pure 8
qtnb = liftA2 (*) cbwc mdzm
dwzg = pure 16
nggz = pure 6
zsmn = pure 4
hnng = liftA2 (*) rqtc cbph
qjbg = liftA2 (*) tjcz thwh
fqtt = liftA2 (-) humn jvzc
gwqq = liftA2 (/) zffv jwmg
wqqh = pure 3
slzl = liftA2 (*) frhj nsjn
mljb = pure 4
wcrr = liftA2 (+) mhnh tgzm
fgnd = pure 5
ndps = liftA2 (*) wjdd hgbz
rjqv = pure 7
cftz = pure 2
thdb = liftA2 (*) gqpf ccrg
zffv = liftA2 (+) tddq qpdb
jqmv = liftA2 (+) dhpt nfvw
mjmc = pure 17
hwvn = pure 19
bngh = pure 2
pnrp = pure 4
jtjc = pure 2
glzn = pure 13
bbmz = pure 7
hjwt = liftA2 (*) dhtw tpjh
prlg = liftA2 (*) gdcz ljsb
jlbt = pure 3
wmwq = pure 4
fqwr = pure 3
qzvd = liftA2 (-) vtff lpcb
bjhf = pure 5
tllg = liftA2 (+) vpqs dcfb
gnht = pure 5
qpwh = liftA2 (*) qlmp gcvh
zcvd = liftA2 (*) svrv bwsq
wbzs = liftA2 (*) ntzh rhvw
hrqs = liftA2 (*) jhqr vhhr
hpfc = pure 2
bqtt = pure 4
nchg = liftA2 (-) jznm zzlw
gpwn = pure 3
hcwt = pure 7
wcvv = liftA2 (+) bfcn vmcn
rwfm = pure 2
mgmr = liftA2 (+) gnvg fshs
dvnc = liftA2 (+) nhfw nrzh
tddg = liftA2 (*) chpw wfqb
djlv = pure 2
nbrv = pure 17
vpth = pure 15
ccrg = liftA2 (*) nggz prht
cjbz = liftA2 (+) gswq ppcg
gbdg = pure 6
bnfw = pure 16
dlpb = liftA2 (*) nmpj dnpd
qvgz = pure 11
swsc = pure 3
sctw = pure 2
fjrq = pure 3
hblv = pure 5
qpvf = liftA2 (*) hgqf zrtc
cmms = liftA2 (-) jsjd tbth
tstv = liftA2 (/) dplp nnjb
pgzc = liftA2 (*) rnds qtrs
scwc = liftA2 (+) cwsc ppmn
nwcn = pure 12
nzpn = pure 13
vssf = liftA2 (*) ncwm rzwt
ljsh = liftA2 (*) nggd htjn
jdgt = liftA2 (*) pgzc gnht
scmj = pure 3
lgdd = pure 3
pwgf = pure 3
btml = liftA2 (*) mtjr hwmd
msvj = pure 1
rmpc = liftA2 (+) qmfm rrws
qccw = pure 9
nvqd = pure 2
cvpw = liftA2 (*) bbtq smzb
rjvr = liftA2 (-) hzcg tgtp
ctlm = pure 2
nrzh = liftA2 (*) btsl lgqq
mnmq = liftA2 (*) jqtr qzct
jdzs = pure 2
pbff = pure 2
zhzc = liftA2 (+) gcfc nmfc
bwwz = liftA2 (*) mztz zgfb
wldl = liftA2 (*) jdfv wjwp
brns = pure 8
zsfr = pure 1
lccj = liftA2 (-) qjbg mzbz
lnbv = pure 5
qbzq = liftA2 (*) nnws hlvd
hlwz = liftA2 (*) dvhc ngdf
stbf = pure 5
hvgv = pure 3
dqjb = pure 3
zpfg = pure 2
wmzn = pure 2
ssdb = pure 3
sdsg = liftA2 (+) cccn msqr
jdzc = pure 11
blsf = liftA2 (*) pnmj bngh
dcpd = pure 3
ptmd = pure 3
wlch = liftA2 (-) rgdw nlqt
tsdf = liftA2 (*) dvcz mglc
jmjw = liftA2 (/) dzdf lpcg
prvw = pure 3
mcdz = liftA2 (+) bqtt wpfb
mrfv = pure 12
zqvt = pure 5
dlph = pure 12
wdpv = pure 5
wpfw = pure 3
wwwc = liftA2 (*) qvds ztjs
rjfs = pure 5
jvdd = pure 15
tjvl = liftA2 (-) dhvd wfqq
fppj = pure 12
mgzw = liftA2 (+) dfmg mlnf
cnrn = liftA2 (*) nswf mstq
mhsd = pure 2
bzdd = liftA2 (*) srzw srlt
wgjt = liftA2 (+) hrvl gznh
zbmj = liftA2 (*) jtjc rvdz
gldg = pure 7
vgsr = liftA2 (*) vwmp mvvj
grqv = liftA2 (*) qpls hchl
vcgw = pure 2
ddcb = pure 10
nwhj = liftA2 (*) zzlq lzdj
fndj = liftA2 (*) ppdj hbtv
cwcv = pure 5
qzzs = liftA2 (-) zzmg djgj
qntv = pure 2
rhln = liftA2 (*) lqvp mmgv
zpwf = liftA2 (*) nqfw tmjj
plvm = pure 2
hcmb = pure 5
wgwv = liftA2 (*) jfpl wlhm
cmbf = liftA2 (*) spzt lhcn
drdc = pure 5
swnc = liftA2 (-) dsnd tnvf
zvrs = pure 2
bvhp = liftA2 (*) mgds gqbq
rchm = pure 3
clll = liftA2 (+) tmmz thqn
gplr = pure 11
gwww = liftA2 (+) jcmg ccvh
tzlt = liftA2 (+) zvgj phdc
zhgr = pure 2
wpfb = liftA2 (*) stcj tfqj
lcqs = liftA2 (+) mmzw dpvw
jctj = liftA2 (*) flhq wclf
zfdf = pure 3
wssf = liftA2 (+) vgft zgvh
wjrm = pure 10
vncm = pure 4
lttb = liftA2 (*) gpwn hdpf
zlph = liftA2 (-) smbf hcmb
mjpl = pure 2
fwgr = liftA2 (+) hvlv bzdd
chvp = pure 4
rptg = pure 7
zpcv = pure 5
tzfp = liftA2 (/) bjnf sfgh
pmzj = liftA2 (+) fwhp wcvw
jmdn = pure 3
nzjg = pure 11
cjzn = pure 5
lzbf = pure 3
ltsn = liftA2 (+) hqqp zbfs
hlwv = liftA2 (*) rbfv wtnt
dvvp = pure 5
mzpf = pure 2
rrmg = pure 5
hqqq = pure 5
wjwp = liftA2 (*) jdzs hsrq
mlqm = pure 8
sntl = pure 5
phdc = liftA2 (*) wgjt bqcb
vhgq = pure 4
vcbv = liftA2 (+) wqtw qdfm
qvnj = liftA2 (*) vcmg nsrm
mwzc = liftA2 (+) thdb scjj
nslr = pure 4
zqvd = pure 3
wqsm = pure 6
tbzv = liftA2 (*) zzvh ghch
swtb = liftA2 (*) pbhn hhqv
hcvh = pure 16
tczg = pure 2
mnfg = pure 7
qnrt = liftA2 (*) mtml tjjs
vnwg = liftA2 (+) rslr pflz
fbnl = pure 3
wdng = pure 2
tqdf = pure 11
wgfd = pure 8
jbwv = liftA2 (*) hzjv fphs
rmvv = pure 5
nqvq = pure 3
gcld = pure 10
slbf = pure 5
rhwv = liftA2 (*) hrnv qvtp
rwdw = liftA2 (*) dgvf dbhl
hqfv = pure 15
hnmz = liftA2 (*) tqpv hjdd
smjz = pure 3
ztvv = pure 10
tscq = liftA2 (-) zjwz jjjt
zchz = liftA2 (*) qbjd rzzz
bpns = liftA2 (-) wgrt brfg
ljbd = liftA2 (+) gfhl pmzj
tfqn = liftA2 (*) cczl ztvv
ndpn = pure 3
btbn = liftA2 (+) wlqt wdpv
cbsp = pure 4
rlfn = liftA2 (/) mslj jlsg
srgf = pure 2
gcww = liftA2 (/) cqhd nvqd
dshb = liftA2 (*) tppn jrmg
cnjr = liftA2 (/) fnwv tqrq
fstv = pure 5
nvgq = liftA2 (*) sdfm fbwc
cmrt = liftA2 (+) chht wncd
pncc = liftA2 (*) hpnn nwqw
gfsb = liftA2 (*) jqfl qszr
hlng = liftA2 (+) lszc hjrd
nldc = pure 20
wsdr = pure 9
dvfp = pure 5
ffqv = liftA2 (*) hcdc prdt
hjwh = liftA2 (*) gbsl mjpl
dtpf = liftA2 (+) wphb tblh
bdww = pure 12
hcrm = pure 5
vzfc = pure 6
rvjc = liftA2 (*) rwjl ntzw
sjqq = pure 13
lrvl = pure 2
bszg = liftA2 (+) zhgr wnnf
plzr = pure 19
bcpv = liftA2 (*) bgzj dfbh
qjjd = pure 16
csjp = liftA2 (+) glgt hqjf
bgtp = liftA2 (*) rtnm hbdh
ctqr = pure 2
hqsp = pure 2
rjww = pure 2
fnpj = pure 17
lwfm = pure 2
msff = liftA2 (-) vlgf qjgt
mgds = pure 3
vrzs = liftA2 (*) brng rpnq
qwph = liftA2 (+) rgfh msfq
prjh = pure 2
bsqc = liftA2 (/) hlng tntr
zcwc = pure 2
fhpw = liftA2 (+) rmnr srcq
dplp = liftA2 (*) ncvh mjvl
mdgl = liftA2 (+) bqht lztt
tdch = pure 6
ngvh = pure 10
cbsb = pure 11
ndtc = pure 3
ngsm = liftA2 (*) qgqp pnzq
gbfm = pure 4
jlsg = pure 2
cmmf = liftA2 (*) gbtc rhqb
zbtz = pure 3
bqhf = liftA2 (+) zvcw vqfq
czsf = liftA2 (*) ddll hlmh
vdvd = pure 4
dzgh = pure 11
jqhr = liftA2 (*) ssdr vfbf
fmvz = liftA2 (+) gvgb cclh
dhtw = liftA2 (*) hfrz mclw
gtvw = liftA2 (*) pqdc dqch
tgzm = pure 11
tqrl = pure 3
wmwn = liftA2 (+) tfrr mhjs
lvpq = pure 1
tqrq = pure 2
mcsc = pure 4
lszc = liftA2 (/) bpll lnfg
hwwm = pure 18
jqmz = liftA2 (*) trpm lstl
phlw = liftA2 (*) npgp rjqv
nsvt = pure 3
tgtp = liftA2 (*) ctvm vpjw
jjzc = liftA2 (+) lmqm jmcf
qvjs = liftA2 (+) spzc jrdq
qzph = pure 2
pnzl = pure 2
nfdz = pure 7
mzgg = pure 10
srrv = pure 13
nnjz = pure 5
nfhv = pure 2
rdgt = pure 3
tfmq = liftA2 (*) gvwq grtl
cjrd = liftA2 (*) bgtg hswl
wtnp = liftA2 (+) fqbr hggn
bvlv = pure 2
qdsg = pure 7
cnjg = liftA2 (*) zsrs gtfc
ffvl = pure 4
zpmq = pure 3
mbmg = pure 5
rfbv = pure 10
hcqj = pure 5
sqzv = pure 4
lsbv = liftA2 (*) wrff jvdd
htvj = liftA2 (+) mtzp wrmh
ddfm = pure 5
qmfm = liftA2 (/) mjzd spct
spcc = pure 17
fvcn = pure 20
fbgz = liftA2 (+) nqmm pwcz
sfzn = pure 6
vjnd = liftA2 (*) grnb ffqv
tpjh = pure 2
frbr = liftA2 (+) dbht rgpc
nhtr = pure 3
dtvr = pure 8
cpwr = liftA2 (-) zhrs tcbz
dsnq = pure 4
jshl = liftA2 (*) rvjc jhdc
ljpg = liftA2 (-) zzdv lbsd
tmmr = pure 9
fdpq = pure 2
hdqf = pure 5
jqtr = pure 2
bpct = pure 3
ggzj = liftA2 (*) ctqr wssf
gcpq = liftA2 (+) tlzg wdqs
vqrn = liftA2 (+) mwgz bjqp
bppf = liftA2 (+) hddh sqgq
vdmp = liftA2 (*) qrhv mpgw
mwqn = liftA2 (/) pbfj mzvv
fgfg = pure 3
hhjv = pure 17
dhbb = liftA2 (*) jfbw wlzg
nbsf = pure 5
rslm = pure 13
dvss = pure 19
dwsv = pure 3
fsrg = pure 16
prvm = pure 2
hblr = liftA2 (*) jbvr jqts
wdcn = pure 13
bmfs = liftA2 (+) pnbv rnls
mnms = liftA2 (*) sfqw sfrv
phnv = liftA2 (+) vnft pprw
tfmw = liftA2 (+) dsll hwjm
brwh = liftA2 (*) sntl mtrw
zgsr = pure 2
qwhh = pure 3
tlpz = liftA2 (*) tmvc sdlv
wbwv = liftA2 (+) zhmn hdvc
jwzn = pure 7
sfwf = pure 3
mgmb = liftA2 (*) ndtc pbgc
ngsf = pure 4
vwfn = liftA2 (+) qvlz ghcl
hcdp = liftA2 (+) gfsb qzph
qvtp = pure 2
qglg = liftA2 (*) mczm wwhh
lssr = liftA2 (*) jthc dbrt
gcwt = pure 3
jzbm = liftA2 (*) dghp tscd
ltft = liftA2 (-) gwtl cmzt
bzcd = liftA2 (*) stnh mzhm
nfpn = liftA2 (*) gjhd jztm
mlnn = pure 2
fqft = pure 8
gfpp = pure 8
flmd = liftA2 (*) sfwf smjz
zcvh = pure 3
bmnn = liftA2 (+) grqv rmcv
qnsj = liftA2 (*) scmj mppn
tbjg = pure 4
njdw = liftA2 (+) mgjp mjpf
vccs = liftA2 (+) lnbd lvjf
zdfz = pure 3
pbhn = pure 17
fmjd = pure 10
mjcn = liftA2 (*) vrvs qvlq
zwqv = liftA2 (*) zqvd jzln
bhfj = pure 4
mjgm = liftA2 (-) rfmd nqmg
rnrm = pure 2
brzn = pure 2
hjnl = pure 5
dzhp = liftA2 (-) wzhv qjcn
vjbn = liftA2 (+) fstb rjmh
vlst = liftA2 (+) qnlg fjfv
dmzf = liftA2 (*) mmzm tnnr
qwvn = pure 3
mclw = pure 2
dhtf = pure 2
wrgb = liftA2 (+) zvpl lltr
ssvs = liftA2 (+) zjrg tbsd
rcwr = liftA2 (*) gvwh nchp
cpcd = pure 3
prfm = pure 4
vhhz = liftA2 (*) gmpz clws
gtzp = pure 8
fbwc = pure 7
dctr = pure 3
tgqm = pure 7
qmtr = liftA2 (+) mjzm qpvf
qbjd = pure 2
ngtq = liftA2 (-) rprp cmwp
zrtf = pure 2
ssbq = pure 2
dpvw = pure 15
rbgz = liftA2 (+) wtbg mrfv
svvz = pure 2
ccvp = pure 4
fmbs = liftA2 (*) hglh qzwb
ljtq = pure 3
cbwc = pure 4
srsg = liftA2 (*) tqqv zcwq
zqjl = liftA2 (+) lzpw zbwc
zdhv = liftA2 (+) flmd mmgp
npbs = pure 10
mhnh = pure 2
tscd = liftA2 (*) nsln hzrz
pbhd = pure 4
ldrw = liftA2 (/) btrt wpmm
zlbn = liftA2 (+) dtvr hgsr
pwjc = liftA2 (*) rgfm rfpp
rvtm = pure 2
zpqr = liftA2 (+) dhtf wfbv
glqm = liftA2 (/) zpqr fqwr
hlcj = pure 4
wzvg = liftA2 (/) jmgz zqtb
cjpm = liftA2 (*) ndpt wqfv
pvcw = liftA2 (*) fsbz tzlt
mnwm = liftA2 (*) dvpw zhhm
clws = liftA2 (*) ptvc lhrm
zvgj = liftA2 (*) svzm hrmm
fvsc = pure 13
fmzw = liftA2 (*) zjnr csrz
dzrf = liftA2 (*) jtnc hqsp
zlwh = pure 3
pwmd = pure 2
flft = liftA2 (*) shzs bjnm
tqfv = liftA2 (*) ptvl jfld
bgtg = liftA2 (*) zmgl hqnl
qlhd = liftA2 (*) ldzp cnnz
zwwq = pure 1
jjpm = pure 14
wzhv = liftA2 (+) tpgr pttl
vlgf = liftA2 (*) tssl lmvt
gnfg = liftA2 (*) cggn pmpn
sffq = pure 8
fbqz = liftA2 (+) zqdc nbjm
vhng = pure 13
zzwt = pure 2
qzgd = liftA2 (*) zlsq frjt
gzmq = liftA2 (+) vzhw qwqr
fvrq = pure 19
gctq = liftA2 (*) nrch ctgl
rdzh = liftA2 (*) jthv shsv
mqbv = liftA2 (-) jdgt wbrs
vmbr = liftA2 (*) fvsc cqgf
fppt = pure 10
pzzm = liftA2 (*) nwnh fsgd
lchq = pure 4
fbws = pure 1
qfpd = pure 8
srzw = pure 11
cwsc = liftA2 (+) rjzw hszg
nfwb = liftA2 (-) lnvg zwmh
nwrd = pure 2
jrjs = pure 2
gjvn = liftA2 (*) fvcc lfcz
tmzr = liftA2 (*) pbqh fzvm
cbdp = liftA2 (*) wzvg msdv
zlgw = liftA2 (*) qwhh jcjq
nvnh = pure 14
rrbn = pure 3
pjlf = liftA2 (*) jmmr mbqp
qngd = pure 5
nmhz = liftA2 (+) pncc drpt
bljd = pure 5
fqlc = liftA2 (+) nzpg qvpm
whhj = liftA2 (+) bzjj qfms
hfvl = pure 11
pnbv = liftA2 (+) cnjr hlnh
bgrg = liftA2 (/) lssr fvfj
vcss = pure 2
gnvg = pure 1
vgts = pure 1
bpjh = pure 3
dhht = liftA2 (+) vdds tlbr
whdm = pure 5
tjcz = pure 7
gjvc = pure 2
vflg = pure 3
dtwp = liftA2 (+) nvgq pjzf
gwtl = liftA2 (+) hbph ngtq
zwds = liftA2 (/) djjg wwwt
bfsf = pure 11
gvwq = pure 3
rdgj = pure 5
pprw = liftA2 (*) vzlr stbf
gmzl = pure 20
scmn = pure 2
tncz = liftA2 (+) vqhz nfcq
sfsl = pure 5
hmhn = pure 3
zvfv = liftA2 (-) hltv pjdr
phdn = liftA2 (*) zlts rjpw
nrhb = liftA2 (*) ddjw tjdh
nqmg = pure 6
nsjn = liftA2 (+) bdsr vmbr
bnmd = liftA2 (+) chfc phnv
djsm = pure 7
lztt = liftA2 (*) dnlg mmtb
qjgt = liftA2 (*) rdzh rcss
dbhl = pure 20
zzlq = pure 2
btrj = pure 7
prdm = liftA2 (*) mhbb vrzv
wjwl = liftA2 (+) zspq cmrt
pwtr = pure 2
tsnb = liftA2 (-) zwqv ghwp
rwtt = pure 5
nzvn = liftA2 (+) qqnq gzsp
ffwm = pure 3
lnwn = pure 2
nnws = pure 3
bpqn = pure 3
cbph = liftA2 (-) pvcw qpwh
mgfs = liftA2 (*) wcvv dnsj
tbrq = liftA2 (*) spcc rjmz
jgls = pure 3
pllq = liftA2 (+) lbpv dhgh
rnls = liftA2 (*) msvh cchj
qfht = pure 9
dwsq = liftA2 (+) mtzt mjcn
hltv = liftA2 (+) jqtj dbrq
mqpr = liftA2 (*) rsbb tbrq
tpwt = pure 2
fqbr = pure 5
dsnd = liftA2 (/) dwsq tpww
hjdv = liftA2 (/) hdcw dpst
rtnm = pure 3
tqqv = liftA2 (-) jzbm gmzl
lgfn = liftA2 (*) hbjl qjhj
wjqd = pure 11
vpvv = pure 5
btcn = liftA2 (+) rnqm svwm
hwbc = liftA2 (*) qfmj szcb
vrbp = pure 2
rldv = pure 4
jznm = liftA2 (*) fflq nlvv
rzsf = liftA2 (*) ndps vsjp
crss = pure 2
vsmj = liftA2 (-) bvrr mmrf
bwbm = liftA2 (+) sqtr vttq
ptjz = liftA2 (+) bnqb vzfh
qqfq = pure 3
jrmg = pure 5
chld = pure 2
cchj = pure 7
jcws = liftA2 (/) lwqq jwdq
nzpg = liftA2 (*) tmrn clzb
jcjq = pure 7
hppn = pure 16
ngpp = liftA2 (+) ngtf zdhv
jstz = liftA2 (+) bbcc bdww
htnm = liftA2 (*) mzmm ssdb
drhd = liftA2 (*) jrpn rhgt
jncv = pure 4
pbqh = liftA2 (+) vnwg trgv
fdsj = liftA2 (/) swnc zlwh
pqgn = liftA2 (+) rcdg tgqm
qfms = liftA2 (+) bwbm bqhf
jthv = liftA2 (*) jwzn mvwr
ldcd = pure 13
hcfm = liftA2 (*) pzdm vrpw
tmvc = liftA2 (*) dqjb fwpn
qpdb = liftA2 (*) dbrv cmbj
dwqf = pure 2
lcvr = liftA2 (*) ssqs nmcr
blww = liftA2 (*) hcgp nznl
ghcl = liftA2 (*) rphf ldzq
dhgh = liftA2 (*) cftz jpjc
zzfj = liftA2 (*) wnvb svvz
ptmg = pure 3
dvbb = liftA2 (*) qwgc dzhp
wjvz = liftA2 (*) crvz mgrb
dhpt = pure 17
jsqn = pure 4
phdb = pure 10
zzlw = pure 1
llcd = liftA2 (*) ztjw rnlc
crld = liftA2 (*) sdsg fpdc
jfnt = liftA2 (+) rqlv hlqg
dbsp = liftA2 (+) rzlh jsqn
wzdj = pure 5
szcs = liftA2 (*) bglw cnsh
wwqm = liftA2 (*) bbdm tlwp
dnrs = pure 5
mdgb = pure 6
mmzm = liftA2 (+) ggzj gwww
cphp = pure 5
wbrs = liftA2 (+) jqmv pzdl
qvnp = pure 2
wpqr = pure 15
ccmz = liftA2 (*) wncw nzpn
frtq = pure 5
dpqn = pure 2
grnb = pure 3
brjj = liftA2 (*) lfjp clfq
hjbn = liftA2 (*) ndpn qwvn
msfq = liftA2 (+) gctq blgq
wtpm = pure 2
gbsw = pure 3
mfvr = liftA2 (+) llcq slgm
jcmg = liftA2 (+) cwhp fjnj
tfzl = pure 19
spcz = pure 9
cqpp = liftA2 (*) tpzb sjld
qqhb = pure 2
nhst = liftA2 (-) cjpm gghd
ztjw = pure 2
wwsn = pure 4
dfcc = liftA2 (*) mwnz pnbt
zjsh = pure 5
ppfp = pure 2
rcss = liftA2 (*) qbqs fqtd
dcmv = pure 9
njfv = liftA2 (+) tfmw zbdh
bvqq = liftA2 (*) bwhh nlhz
jswt = pure 5
jpzc = pure 4
zltq = pure 1
pshd = liftA2 (-) lqlw mdgb
sgnm = pure 2
gbbq = pure 5
zmgl = pure 5
ddll = pure 2
vstm = pure 14
tjdh = liftA2 (*) hvbp hfmn
pgfv = pure 3
pdrt = liftA2 (/) ltvh pnzl
vpvf = pure 2
jbdd = pure 2
zwqn = liftA2 (-) ldnq hcvv
sgwj = liftA2 (-) vmhg dwpl
wjdd = pure 3
qwdv = pure 2
zbdn = liftA2 (*) qqfq llcd
cclh = liftA2 (*) nntn vzgp
cwlg = liftA2 (*) lmcq pnbm
bpwc = liftA2 (+) wgqm rhlb
jzpf = liftA2 (*) lbcq dppz
fstb = pure 3
mczm = pure 2
mttr = liftA2 (*) vhgq qljl
mmsw = pure 2
wqtt = liftA2 (*) ndmc jngv
mbdz = pure 8
mdgh = pure 8
zhrc = liftA2 (*) phdb pwnl
wjlw = liftA2 (+) dwhf dtns
pbvr = liftA2 (*) ldrb dnvq
gdvb = liftA2 (*) rcns pfjs
ptvl = pure 2
wqtw = pure 4
zjnr = pure 3
nqnn = liftA2 (*) fcvf gbdg
vhvp = liftA2 (+) bgnn jcsh
rqtc = pure 6
wzcw = liftA2 (*) ldfp jjbt
ssgw = pure 2
jhbf = pure 4
ndmc = pure 7
pvvz = pure 2
zhmn = liftA2 (+) dfcc tmvl
nswf = liftA2 (-) fjms wsmp
mtjr = liftA2 (-) gdvg qbsm
zgbb = pure 3
vpqm = liftA2 (+) jqqw bwnj
pqfg = pure 2
bwcz = pure 5
prht = pure 4
qtrs = pure 5
rslz = pure 3
njls = liftA2 (*) tmmr sctw
tbqc = liftA2 (+) qtnb twjg
ntbv = pure 1
dpvt = pure 6
shhr = liftA2 (*) wncg scgw
nmfc = pure 2
wmdt = pure 16
hgqf = liftA2 (/) mgsh pbff
hnjc = pure 2
hsgn = pure 4
hgwl = liftA2 (+) vgsr ttzb
qmvr = pure 2
gcvh = pure 3
fhpp = pure 3
jwsj = pure 2
mjjf = liftA2 (/) cjsd bvmw
vgcg = liftA2 (+) lgcw jtfj
tthn = liftA2 (+) jcws qdsg
tfqj = pure 5
mrjs = pure 3
dcsb = pure 2
prnv = pure 3
dsqj = liftA2 (+) tsdf wphl
npst = pure 12
gglj = pure 2
htlq = pure 5
sjjl = pure 20
pnzq = liftA2 (*) tfnn scpz
ztwq = liftA2 (+) gtjp wzfg
zvbt = pure 3
hrnz = pure 5
bggc = liftA2 (+) sfsl dpvt
ssvq = pure 9
jldh = liftA2 (*) hcqj cqnp
slmj = liftA2 (+) qvbl npst
dqgq = pure 17
zthw = pure 2
wnfn = liftA2 (+) jthn lrsg
nwpb = liftA2 (/) mmjw dgll
lpjr = liftA2 (+) whhj tddn
bpnb = liftA2 (-) ngsm wrgb
cdvw = liftA2 (*) lpjr dmnw
njgs = liftA2 (+) fpgc ndff
grrr = liftA2 (*) tfts ljgz
tmvl = liftA2 (*) ljvj svgf
nfmp = pure 3
qchv = liftA2 (+) jbwv mccg
zjwz = liftA2 (*) qvhf ghsz
gvwl = liftA2 (+) cqpp wltv
mhvg = liftA2 (+) qnrt ndjs
gvld = pure 2
gtwm = liftA2 (*) mdfq qdfb
wsgm = liftA2 (*) fddr cqqs
vnws = liftA2 (+) lhbs thnm
mvwj = pure 2
dgzv = liftA2 (*) dbsp bfhf
tlzg = liftA2 (*) zpnf pwmd
brcq = pure 5
ptmf = liftA2 (*) dwgb wngv
tbvd = liftA2 (*) mcbz wmwn
cqgf = liftA2 (*) ctlv fppj
vwjh = liftA2 (*) mmgs rwdr
qjnr = liftA2 (*) pzdz wjpv
cwhp = liftA2 (*) zqmp zlwg
fjtm = liftA2 (/) bmnn ptqz
dgls = liftA2 (-) wpvc mgtj
ltfj = pure 7
bzfd = pure 3
gzrg = pure 2
hpnn = liftA2 (*) tzfp nhsd
hwcq = pure 2
tbth = pure 7
jsqg = pure 3
qcql = liftA2 (*) lqvb mrjs
djgc = pure 2
chbz = pure 3
jwmg = pure 2
wdfp = pure 5
qvdd = liftA2 (+) ggdj dmvg
mlwd = liftA2 (*) rvmp rvss
dmnw = pure 3
gdcr = pure 4
pcvc = pure 9
frjt = pure 3
shdm = pure 5
zcnh = pure 3
wlhm = pure 3
nnds = liftA2 (+) crwm nwpb
btjz = liftA2 (*) rdvt pbvr
ptvc = pure 2
hhrr = pure 2
tbhz = pure 16
jdfc = liftA2 (*) bwpv ncgt
pwnl = liftA2 (+) qnsp tqdf
rlbl = liftA2 (*) wpcs jqtg
gzgp = pure 2
mzhm = pure 4
hdpf = liftA2 (*) lfdd dbrj
qvds = pure 5
tdqv = pure 5
pbnc = liftA2 (-) flft dgwl
mdfq = liftA2 (*) qvnp wdms
lqvb = pure 3
nlhz = liftA2 (+) zbtz mvnl
vvlc = pure 2
vpmd = pure 11
glpb = pure 7
vrzv = pure 2
ppcg = liftA2 (*) bjhf mrmn
gprr = pure 2
cddq = liftA2 (*) fqms stcs
lswz = liftA2 (+) rbhb rstc
bfcn = liftA2 (+) splb cnhh
mrmc = pure 3
crvz = liftA2 (+) vnww ztzz
wqfv = liftA2 (+) vhcc vsbz
frzw = pure 7
plft = pure 2
svzm = liftA2 (*) dsfh qhgn
lcqf = liftA2 (+) lfqr nwmw
mzmr = pure 10
nhtg = liftA2 (/) bnmd zgbb
vszc = liftA2 (-) qzgd gjvn
zfdl = pure 6
hjrd = liftA2 (+) ldsg cnrn
mtzp = liftA2 (+) qzrv tslf
wsmb = liftA2 (*) rmpc lgdd
lhzr = pure 5
szgj = pure 2
qvbl = pure 1
dwrj = liftA2 (*) twqp ncrs
fzlc = liftA2 (*) tscz wjrm
vrqz = pure 6
rfmd = liftA2 (+) hwgg brmm
mslj = liftA2 (+) lfhs nrst
dzdf = liftA2 (*) vstl bgrg
jchz = pure 2
dgwl = liftA2 (+) mbrc jshl
jdnv = pure 2
wfbn = pure 4
dbrj = pure 5
tqpv = liftA2 (*) fzbj vtdn
bvrr = liftA2 (*) ffwm gtzz
svwm = pure 6
tddq = liftA2 (*) vvfq tbjg
jsjd = liftA2 (*) wjlw fqrr
clpf = pure 5
vbsd = liftA2 (/) hjwt cgfp
pszc = liftA2 (+) swmc vqsz
jqts = pure 6
tssl = liftA2 (+) htvm vjmf
jrpn = pure 5
qftr = pure 2
zgvh = liftA2 (*) dctr cjbz
vzfh = liftA2 (+) sdwq rgnv
jvzc = liftA2 (*) jqhd gwgn
hfcs = pure 2
hhvd = liftA2 (*) btbr jjdn
qdfb = pure 3
dhvd = liftA2 (*) cphp crld
rwbw = pure 13
nggd = pure 3
cvpf = liftA2 (*) chvp hflv
ctgl = pure 2
tvhs = pure 4
gmpz = pure 4
gjnm = liftA2 (*) frzw qvgz
qfwr = pure 2
nwft = pure 5
jszc = liftA2 (+) srsg ffdv
tdlf = pure 5
qnwt = liftA2 (-) ddjh dsqj
wzvl = liftA2 (+) dvfp msvj
djfb = liftA2 (-) wnfr bbmz
ltcm = pure 2
ddqm = pure 10
zppb = pure 12
hflv = pure 17
vzmq = liftA2 (*) scmn ddns
scpz = pure 3
nmpj = liftA2 (*) nhtg vcss
vtff = liftA2 (/) qszg ztvq
dnrb = pure 3
mrlh = pure 2
stcj = pure 5
lmcr = pure 17
sbhb = pure 1
zrvl = pure 3
rctr = pure 17
cgjf = liftA2 (/) vgfd fnzr
hlnh = liftA2 (+) hwvn wfbn
hrzl = pure 10
lfsd = pure 2
hrcv = pure 20
rhqb = pure 2
qrhw = pure 12
lmqf = pure 2
gfbc = liftA2 (*) qngd rrmg
hlgt = pure 2
phjw = liftA2 (*) cdvw vljq
rrws = pure 1
gghd = liftA2 (*) jrgw fmql
frtl = pure 10
rcdg = pure 12
fjvf = liftA2 (+) crzd lddf
ggdj = liftA2 (*) wlgc ljlw
fmvt = pure 2
pnmj = pure 3
rcns = liftA2 (*) qfwr rvrj
zqmp = pure 3
bsmz = pure 2
rjzw = liftA2 (*) lgjm vhng
jdvv = liftA2 (*) hrtr pnrp
mbtd = liftA2 (+) nlpl wtnp
qjqs = pure 2
tlfd = pure 4
hvlb = pure 3
ntsp = liftA2 (*) hjbn mplg
tlbr = pure 3
flld = pure 5
twcq = pure 5
ggtc = liftA2 (*) pqqz zcpn
tscz = pure 3
zhzl = pure 2
shzs = pure 10
mrwm = pure 4
zlts = pure 14
lwjz = pure 4
lqvp = pure 9
lgqq = pure 2
gjhd = pure 3
vqhz = liftA2 (*) mbdz hrnz
vqjf = liftA2 (*) jftm vfsw
dwpl = pure 5
flnb = liftA2 (+) rjff mjmc
cnzm = liftA2 (*) hrgh hfhn
spzc = liftA2 (*) czsf zvsm
hzbh = pure 5
ljlw = liftA2 (*) qtdr zcwc
vmpw = pure 5
cwmm = liftA2 (*) tczg gjnm
nbjm = liftA2 (*) zsmn jbmg
dbmt = liftA2 (*) vjtq vbfg
wdtp = liftA2 (*) bwcz btbn
tjnh = liftA2 (+) fnqw vstm
phrq = pure 13
ncjl = pure 7
pcdv = liftA2 (-) fftf ddqm
ftrr = pure 3
hrvl = pure 2
cqnp = liftA2 (+) tdlf hcrj
nmcr = pure 3
zmzt = liftA2 (+) sbhb vjnd
srfg = pure 5
htvm = pure 18
dnvd = liftA2 (*) zmfh nqwb
wfqq = liftA2 (*) prlb nfpn
smmb = liftA2 (*) gtzp hqmp
ftnh = liftA2 (+) ddst ppvw
wlth = pure 5
psmd = pure 4
nchp = pure 3
splb = liftA2 (-) ddsl lzpm
flhq = liftA2 (*) nqnn tfhp
snmh = liftA2 (*) ccvp plft
zzmg = liftA2 (+) dwzg grml
lfqr = liftA2 (+) zvjs dwnf
mwcc = pure 5
ldrb = pure 3
zbfl = pure 2
wjpv = pure 4
hhqv = liftA2 (/) rgpp qdnm
wdwj = liftA2 (/) nldc nwrd
bncz = pure 3
gjws = pure 12
gvtw = liftA2 (-) zpwf jhwt
wlsr = liftA2 (*) wdtp tglj
dfjd = pure 3
pjqj = pure 20
qcdj = liftA2 (*) jbqm hblv
wjlz = pure 16
njdb = liftA2 (-) tddg glwg
qwqr = liftA2 (*) vgsn vvmv
ztvq = pure 3
gpgm = pure 2
tddn = liftA2 (*) hpsd qqhj
bfvc = pure 2
dnng = pure 2
rjpw = liftA2 (*) hlgt jlsn
trdt = liftA2 (+) qclt qzzs
mljh = liftA2 (*) gbph mwqn
mjst = liftA2 (+) njcd lcmg
dvpw = pure 3
lgjm = pure 2
ncvh = liftA2 (+) vhhz lzlg
vmjm = liftA2 (+) brtb mbgb
hfhn = liftA2 (+) ssvs ddcb
wltv = liftA2 (*) wwlv hfvw
hcnw = pure 7
lctq = pure 5
jhfp = liftA2 (+) gjws bmsg
jzjb = pure 2
dbrt = pure 2
jngv = liftA2 (+) lgnh wsgm
gnfl = liftA2 (-) hvfd lrlp
qdcs = pure 4
zpnf = pure 3
fsjv = pure 2
bvpg = pure 3
zhbj = pure 3
nwlt = liftA2 (+) chtn sdfs
pqqz = pure 5
qwws = liftA2 (+) rpwc pdzc
lbpv = liftA2 (+) zqwh fssb
cfrc = liftA2 (*) lljs ndlp
gzrc = pure 2
gvgb = pure 1
hzrz = pure 3
jltf = liftA2 (+) blcm lptn
jhqr = pure 3
lbsd = liftA2 (/) qmzb clpf
zqnj = pure 18
ftws = pure 19
zvjs = liftA2 (+) fpjl jptg
fvml = liftA2 (+) vqhs lvpq
fzbj = pure 2
gtjp = pure 1
njcd = liftA2 (+) fqft lqgq
tmmz = liftA2 (*) nnds qtwf
pnbm = pure 4
hwjm = liftA2 (*) bwmp tbcf
wphl = liftA2 (+) mzmr qdjf
hlhh = pure 2
dgvf = pure 12
dfzs = liftA2 (+) hqqq ssgn
hlbq = liftA2 (*) tvhs vccs
vbng = liftA2 (*) spqh pwvm
pbfj = liftA2 (+) wbwv mzfm
bfhf = liftA2 (+) cnnw plmd
zbbv = pure 12
zczp = pure 17
wwhh = liftA2 (+) rlbl fsbf
gbtc = liftA2 (+) hlwv hlwz
tpsm = pure 2
pdbt = liftA2 (+) pjlf srhs
jqtg = pure 2
fbcb = liftA2 (*) nfmp tphz
vvfq = liftA2 (+) qhnc jldh
spct = pure 8
nhqw = liftA2 (/) jqqq bsmz
pvps = pure 2
tggg = pure 12
rjrf = liftA2 (+) htbc frdt
mzbz = pure 6
dfbh = pure 3
hsjh = liftA2 (/) lzfr lqrj
wqsg = liftA2 (*) hpzf zlph
rgdw = liftA2 (+) ntwd pvps
bqcz = pure 5
gdmt = liftA2 (-) btml rslm
ndpt = pure 2
mppn = pure 19
shsv = pure 7
gswq = pure 1
rjzv = pure 5
zhdj = liftA2 (*) jhrh zhzc
grml = liftA2 (+) pqfd fdnr
vqjn = pure 10
wdnj = liftA2 (+) sgcw cgcn
dsdj = liftA2 (+) mbsv mjjf
ssnl = pure 11
mddj = pure 5
rmjp = liftA2 (*) vpvv ppfp
rvdz = pure 7
vjmb = pure 2
ljts = liftA2 (*) hpfc hsjh
lmqm = pure 1
bhfn = liftA2 (*) dvct fbcb
ftzh = liftA2 (*) vqjn crww
hwgg = pure 2
cqqs = pure 3
hjgj = pure 2
jztm = pure 13
ghbc = pure 6
wncg = pure 3
rjmz = pure 2
htbv = pure 11
ndnp = pure 5
rfzz = pure 3
wfgc = liftA2 (+) dpqn tlpz
dvcz = pure 3
qwmt = liftA2 (*) rrbn zthb
hwcm = pure 4
mptj = liftA2 (*) zfdf rptg
tbcf = liftA2 (+) hbvn zhvq
sbqt = liftA2 (*) vfnm pdjp
tphz = pure 3
pnbt = liftA2 (+) bszg gnmt
wnvb = liftA2 (+) gpfh cmbf
qbqs = liftA2 (+) hnfp wjqd
vshl = liftA2 (+) rbvb pjvn
jrpc = liftA2 (+) nrqq hblr
zcpn = pure 5
fnzr = liftA2 (+) cvnq tfcs
vmfl = liftA2 (+) ctlr qjjd
dhhf = pure 5
ndhf = liftA2 (/) cvpw plrw
zvcw = pure 6
fjms = liftA2 (/) vsmj lhzr
bhtd = liftA2 (*) fnpj dptd
vfnm = pure 14
hvfd = liftA2 (+) hpdp mgpj
twcs = liftA2 (*) tdrv hvls
tmlc = pure 3
dsll = liftA2 (*) hgwl vncm
vcmt = liftA2 (*) vjcb snbr
bjnf = liftA2 (*) srgf ftts
scsh = pure 13
qrpr = liftA2 (+) dbmt zbbv
llvf = pure 13
dfpr = pure 7
gvgd = pure 1
lqpl = pure 4
ngdf = liftA2 (*) nbrv wwwc
hbtv = pure 2
lfrj = pure 2
mbrc = liftA2 (-) tbzv ptmf
bhnw = liftA2 (+) qqbg vwmm
gcfc = pure 7
bmfr = liftA2 (*) wflc gzgr
wbrc = liftA2 (*) lnwn cjzn
dgll = pure 2
ddsl = pure 17
vzgp = pure 5
cwmp = pure 4
ddns = liftA2 (+) rrph zchz
znfh = liftA2 (*) fgsd hcss
mvnl = pure 4
mwjn = pure 2
vwds = liftA2 (+) mpcm blww
brtb = pure 7
zwls = pure 7
hhpm = pure 3
gtmz = pure 5
pgcb = liftA2 (*) qdpl dnrb
tcrn = liftA2 (*) qwmt lchq
qzhb = liftA2 (*) frtq drdc
prcm = liftA2 (/) wjwl czhc
mtzt = liftA2 (*) fjvj gjfs
fdqz = liftA2 (+) brwh chjr
plrw = pure 2
gqhb = liftA2 (*) mpgn rvjs
qtjc = pure 18
hrtr = pure 4
mwgz = pure 17
snbr = pure 2
dnsj = pure 3
rrcs = liftA2 (*) qccw ptmd
rnds = pure 5
nbdr = liftA2 (/) smmb vjnm
gczz = liftA2 (*) wjwd jwsj
hqmg = pure 17
zzdv = liftA2 (*) nnjz sfzn
fhph = pure 3
qwgc = pure 2
dvhl = liftA2 (*) bpjh rrpl
rpwc = liftA2 (+) lqgf stbv
gntr = pure 2
wwwt = pure 5
jdcc = pure 1
bmsg = pure 1
blqg = liftA2 (+) vshl dwrj
vssd = liftA2 (*) nsmp wgfd
dfrr = liftA2 (/) zwqn wwld
vpqs = liftA2 (*) rgjv hpcn
wsns = pure 7
thwh = liftA2 (-) prcm spqb
ndzs = liftA2 (+) qwhg pqwf
jfjm = pure 3
hjdd = pure 2
wwld = pure 6
tgzr = liftA2 (+) ljtq lvwj
hvls = pure 4
mdzm = pure 3
fmjw = liftA2 (*) dphm wmzn
lbrm = liftA2 (+) dplt ndvz
vzlr = pure 3
tlch = liftA2 (-) ljbd fndj
vcmg = liftA2 (+) cbdp dvnp
ncjj = liftA2 (*) lfrj fbgz
ssgn = liftA2 (*) fpvg qdcs
hbdh = liftA2 (*) sfqb btcn
stcs = liftA2 (+) mdwj shhr
mqzv = liftA2 (*) wzbf rslz
sjlw = pure 3
smzb = liftA2 (+) zwnh wmdt
gpch = liftA2 (+) gwdq zlgw
lglv = pure 2
wflc = liftA2 (+) tdch zwds
lpnz = pure 14
svgf = pure 11
thpp = liftA2 (+) pglz hcrm
ncsb = liftA2 (+) ljlz jmdn
tstt = pure 4
cpcs = liftA2 (*) bbjt hcwt
pwhq = liftA2 (+) rqbs nmzd
tglj = liftA2 (*) jrjs pjjr
tlpg = liftA2 (*) zdfz nmrr
jjjt = pure 16
gfhl = liftA2 (+) tdqv cvpf
ntzw = pure 2
hcss = pure 3
wlzg = pure 3
zwnh = pure 7
rrph = liftA2 (/) sqqt brzn
vstl = liftA2 (+) mrlh dhhf
bbdm = pure 2
vdds = liftA2 (/) hwbc jgjd
tppt = pure 5
ljnn = liftA2 (+) nczc fvml
nfcq = liftA2 (*) srfg pvhj
qnsp = pure 2
drlq = pure 2
qszg = liftA2 (+) vgcz hwfd
fzvm = pure 2
rqhj = liftA2 (*) ptmg wcrr
vnch = liftA2 (*) mbtd htlq
lzpm = pure 4
jptg = liftA2 (*) rwch bhfj
hdtm = pure 4
jcjv = liftA2 (*) rhhp cpcd
wncw = liftA2 (+) nsvt vwwf
mgtj = pure 2
wpjd = liftA2 (*) pszc dhpr
twjg = pure 11
gjfs = pure 14
hnfp = liftA2 (*) ldcd wqns
jmdr = liftA2 (*) scwc wwsn
lbng = liftA2 (+) hjnl rzsf
zprs = liftA2 (+) bjbz nwft
plmd = liftA2 (*) zzwt gvwl
mmgv = liftA2 (+) hhzv lpnz
ppwp = liftA2 (*) jhbf qgjz
zjrg = liftA2 (*) nbdr tllp
nrpb = liftA2 (*) fdbz bmfs
vnft = pure 14
nbjv = pure 6
lpcb = liftA2 (*) hjdv mlgf
bbnn = pure 3
fjnj = pure 2
fmmj = pure 6
zthb = pure 5
lqpm = pure 3
lhcn = pure 4
rnlc = pure 5
sjld = pure 7
ztzz = pure 1
bcvh = pure 3
lrlp = liftA2 (*) rqhj bpct
jjdn = pure 13
tdrs = pure 2
thqn = liftA2 (+) ffsg fbqz
tvwz = pure 3
ltvh = pure 12
vwwf = pure 4
mrmn = pure 2
cnnz = pure 2
ffsc = pure 4
mgrb = pure 2
mcbz = pure 2
gwdq = liftA2 (*) djgc gbfm
rrgm = liftA2 (+) zwls snmh
dtmn = pure 6
tpzb = pure 3
mpcm = liftA2 (*) sfcf jpms
dnpd = pure 2
dqgt = liftA2 (*) tlsg pdtt
tnjc = liftA2 (+) bvlv tbqc
qvmf = liftA2 (+) ncsb mgmb
jppv = liftA2 (+) fmjd fmzw
lptn = liftA2 (*) lrhw rbgz
cjsd = liftA2 (+) cjrd ngjn
clfq = pure 3
jtbh = liftA2 (*) dzjc mnms
dbht = liftA2 (+) pdbt fcjn
vtlz = liftA2 (+) mtpf ccjz
csjz = liftA2 (*) jqhz qmvr
nqfw = pure 5
wtnt = liftA2 (*) qwph dvbb
rvnn = pure 3
nfvw = pure 2
zwmh = pure 5
hqqp = liftA2 (/) nzmv rwlz
wcwl = pure 4
dhtg = liftA2 (*) nqvq blsh
chht = liftA2 (*) mqzh jmnq
gdcz = liftA2 (-) vwgj cqlp
grtl = pure 3
dzvt = liftA2 (+) sjjl vvlc
pbgc = pure 3
bwjq = liftA2 (*) qjqs bncz
jhwt = pure 6
dfmg = liftA2 (+) gcpq jstz
rrpl = liftA2 (/) bgtp tnqc
cppm = pure 3
qlwz = pure 5
pccw = pure 4
qpls = pure 2
dcfb = liftA2 (*) rjfs rllj
llqz = liftA2 (*) bljd ssnl
hvqw = liftA2 (*) nwcn ldsz
dwfs = pure 5
qzwb = pure 12
mtzq = pure 3
gqpt = liftA2 (+) vzfc tbpt
qtwf = pure 3
ngjn = liftA2 (+) qzlq tghv
htwg = pure 2
zrdq = liftA2 (*) nvnh lrvl
djjg = liftA2 (*) ptfh hmgd
dzjc = pure 3
djgj = pure 6
mglc = pure 5
fpgc = liftA2 (*) nfhv cwlg
brmm = liftA2 (/) dvhl qhdp
cnsh = pure 2
lqzn = liftA2 (*) ccbp swnz
gwgn = liftA2 (+) vdps phgf
msnl = liftA2 (/) vwds hfcs
chpw = pure 5
sgpg = pure 10
lhrm = liftA2 (+) lwjz fvrq
mftq = pure 2
tslf = liftA2 (*) hhvd ddfm
wncd = liftA2 (+) bpns wqtt
nwmw = liftA2 (*) bpnb mzpf
jmgz = liftA2 (*) rdgt cfwv
gbfc = pure 7
vjtq = pure 4
lsft = liftA2 (-) tncz gpzt
gpmn = liftA2 (*) jszb brcq
nczc = pure 5
dnvq = pure 2
fcvf = pure 2
glhl = pure 1
qgqp = liftA2 (+) tstv mlhh
vmqz = pure 3
tlwp = pure 11
ddst = pure 5
gjqh = pure 2
nmdl = pure 3
qrhv = liftA2 (*) przl gbbq
lvwj = pure 16
clnz = liftA2 (*) lsft wqsg
zfbf = liftA2 (/) fqtt jppn
rwfc = pure 2
jbmg = liftA2 (/) nlsz mlnn
psbw = pure 7
ljql = pure 13
cvmv = liftA2 (*) jffp szgj
bwnj = liftA2 (+) mqzv cvmv
wwlv = pure 2
qglp = pure 1
qjhj = pure 2
jzps = pure 2
ffsg = liftA2 (-) tqlc fjhp
qjcn = liftA2 (+) tlch qrcn
fjhp = liftA2 (*) glzn cmms
rlpn = liftA2 (-) hnmz qtfs
szcb = liftA2 (+) cqfh gnfr
zqwg = liftA2 (*) gnfg lqqg
lrpn = pure 2
sqqt = liftA2 (*) lvlm trdt
bvmw = pure 2
zpvw = pure 5
rwlz = pure 2
schl = liftA2 (+) gcwt nrcl
drpt = liftA2 (*) lhzq qmtr
bqsb = liftA2 (-) dnfc vlst
jdfz = pure 5
nlvv = pure 4
rjmh = liftA2 (*) lctq lfqf
dwlz = liftA2 (+) cwmm nwhj
dvct = pure 3
tcbz = liftA2 (/) rjvr prjh
tcfq = pure 4
qvcb = liftA2 (/) hwls hpcs
mwhs = pure 16
gznh = pure 5
swnz = pure 3
thcn = liftA2 (*) srrv jdnv
tmbg = pure 2
ljsb = pure 16
qnnz = liftA2 (*) ldmt hhrr
qdfm = liftA2 (*) mwhs bfvc
vgfd = liftA2 (*) qsqw nhtr
cvcc = liftA2 (*) mzrm lmbd
hzjv = liftA2 (*) mcdz prnv
zhfp = liftA2 (*) vrpd wdnj
mlgf = pure 14
nmzd = liftA2 (*) rgbh bpqn
cmwp = liftA2 (*) wfjz gjqh
tfhp = pure 3
--root = liftA2 (*) zhfp hghd
vtnb = liftA2 (+) nrwj rhwv
ltpp = liftA2 (*) vcgw hqdl
wbhc = liftA2 (+) zgtr scrb
wzzh = pure 8
ccpw = liftA2 (*) mhsd zmzt
mtgn = pure 16
drgf = pure 13
rnwm = pure 16
hfhc = liftA2 (*) nwvr zjsh
tfts = pure 4
tjjs = liftA2 (+) mcqw fsqs
glfz = pure 2
ldzq = liftA2 (+) zzgp nbjv
cdgs = liftA2 (+) bldp dtwp
zlhb = pure 4
wclf = liftA2 (*) dcmv gdcr
hszg = liftA2 (+) fcwq htzb
cwzd = pure 2
jbgd = pure 5
jbvr = pure 13
vtdn = pure 7
dppz = pure 2
ldsg = liftA2 (+) gqpt njgs
tfrr = liftA2 (*) vpth fmmj
vvmr = pure 4
ztjs = liftA2 (-) cvcc gtnp
jszb = pure 5
tbpt = liftA2 (+) srhg tblr
fpvg = pure 2
fdbd = pure 12
ljlz = pure 19
lnbd = liftA2 (+) lntr ptrh
twqp = liftA2 (+) zqnj rqsh
mhbb = liftA2 (*) hlnl vbsd
nzsq = pure 1
rdvt = pure 2
ppvw = pure 7
ddjw = liftA2 (-) hlbq vwjh
wgrt = liftA2 (+) vdmp lttb
mvzw = liftA2 (*) plvm qfht
fszn = pure 7
mchv = pure 5
bwmp = pure 2
drft = pure 4
bgqp = pure 7
trgv = liftA2 (-) tbvp qzmc
nwqw = liftA2 (*) vtlz qchv
ntwd = liftA2 (/) llqz rdgj
jfld = pure 7
tblr = liftA2 (*) tlrl rwbw
dmvg = liftA2 (/) bqsb jbdd
nqwb = pure 3
tnnr = pure 2
hzcg = liftA2 (*) wmwz nnwg
fcjn = pure 12
lcmg = pure 8
cczl = liftA2 (+) qrpr jgfg
rgfm = liftA2 (+) vqrn dzrf
fpdc = pure 7
pqdc = pure 5
rdml = pure 1
nttj = pure 3
qszr = pure 7
qmzb = liftA2 (*) qvzl bgqp
pwsb = pure 2
lzdj = pure 19
bldp = liftA2 (*) dvss jhfp
ljvj = liftA2 (+) rwtt prvm
vgsn = liftA2 (-) tcrn ftws
ngtf = pure 10
wzbf = pure 2
pvhj = pure 2
fvdm = pure 14
mmjw = liftA2 (*) gvtw dlpb
jlzw = pure 2
qhnc = liftA2 (*) zczp gzrc
thvj = pure 4
mgjp = pure 1
qgnb = pure 3
nmrr = pure 3
bqht = liftA2 (*) pvvz fppf
fqtd = liftA2 (+) lcqs jllt
nznl = liftA2 (+) nslr qlpn
qlpn = pure 2
rgjv = liftA2 (+) sqzv hbdp
mcqw = pure 6
nnvb = liftA2 (*) ltfj hcvh
sdfs = pure 10
mdmt = pure 2
zhrs = liftA2 (*) jrcb ndzs
rgpc = liftA2 (*) qvql dnng
jllt = pure 7
pzdm = liftA2 (/) gtwm mrhp
pzdz = liftA2 (+) ztwq qglg
czhc = pure 7
jffp = pure 17
mbqh = liftA2 (/) vtzz zvzw
hfmn = pure 2
srlt = pure 2
cmgv = liftA2 (+) lrwv zgsr
wdms = pure 7
rvrj = pure 11
lczw = liftA2 (*) ftrr gbfc
ncvt = liftA2 (+) sgpg rrcs
vttq = pure 6
hcdc = pure 2
vzbv = liftA2 (*) lfqp qtgr
wgqm = liftA2 (+) fdpp dgls
fnqw = pure 3
lfhs = liftA2 (*) gpch hpbj
wfqw = liftA2 (-) spww mlqm
hqvl = liftA2 (/) cddq qwvp
fppf = liftA2 (+) jtbh dqgt
rjff = liftA2 (*) pdvb fnrn
bsvl = pure 10
mtml = pure 3
hrgh = pure 7
ptfh = liftA2 (/) sgws bgwg
ndjs = liftA2 (+) drgf pbhd
gvrm = pure 4
btsl = pure 4
zqdc = liftA2 (*) rbhz nnph
fpjl = liftA2 (+) wtlp dfjd
cnqb = pure 2
hsjv = liftA2 (+) hndr jrtn
nqmm = liftA2 (+) qgnb wzvl
fzzd = liftA2 (*) rchm lswh
qlmp = liftA2 (+) qtjc dfnv
nrzl = liftA2 (*) drhd bcvc
cfmn = liftA2 (/) lsbv hlhh
mtrw = pure 5
rzlh = liftA2 (*) lzbf jfzc
gplc = liftA2 (+) vgcg zvtn
qvlz = liftA2 (+) mjgm ghbc
gnfr = pure 1
spqh = pure 5
csrz = liftA2 (+) jfjm lqpl
rwch = liftA2 (*) wtpm dbgl
hmsc = liftA2 (*) vmfl cfgp
rwdh = liftA2 (*) zpmq mqfb
vjnm = liftA2 (*) ppvj ltcm
lmlt = liftA2 (*) cwmp cnqb
ccjz = liftA2 (+) vqmg pllq
mqfb = liftA2 (+) wfqw hhpm
vsjp = pure 3
lntr = pure 2
zwcl = pure 17
rpqc = liftA2 (*) hfvl mbqh
fcwq = liftA2 (*) hwwm lfdm
bttg = liftA2 (+) rlpn ctvz
lqrj = pure 2
djqc = pure 5
nrst = liftA2 (*) bppf hcnw
wfbv = liftA2 (+) dshb ngpp
svrv = pure 2
zgtr = pure 5
rzbs = liftA2 (*) bgwp pwhq
jzln = pure 3
jnwm = pure 1
lqgf = liftA2 (*) psmd pqgn
zjlh = pure 2
lfqp = pure 3
vbbs = liftA2 (*) mtzq rfrs
smbf = liftA2 (*) lbrm dbfs
jcsh = pure 11
sdlv = pure 5
lwjh = liftA2 (+) fwnf jfqs
tdlm = pure 19
mzfm = liftA2 (*) tsjf cwcv
cfmj = liftA2 (*) wdng ngsf
gtzz = liftA2 (+) hhvv ldrw
phgf = pure 2
ldtq = pure 5
wfqb = liftA2 (-) scsh mtrj
jpmr = pure 2
dvhc = liftA2 (*) hvlb bdlr
rwjl = liftA2 (-) ncjl qtzz
vsrz = pure 2
ctlv = pure 3
zdsb = pure 1
ctvm = pure 8
lswh = liftA2 (*) frtg mdgh
hpbj = liftA2 (-) vhvp jbfp
jbqm = pure 2
bbjh = pure 4
vdps = pure 7
zqwh = liftA2 (+) njdw vqsp
drrb = liftA2 (+) phlw jjrr
mtrj = pure 2
qdnm = pure 2
fsbf = liftA2 (+) dtmn qzhb
fvcc = pure 11
jstj = liftA2 (+) mdrm zqwg
hrwm = liftA2 (+) thcn mnwm
srhs = liftA2 (+) rdml fmjw
bzjj = liftA2 (*) vmqz wqqh
jwhp = liftA2 (+) vgts bwwz
zzgp = pure 5
lfjp = pure 3
bpll = liftA2 (*) djlv fzmp
qbsm = pure 2
qqwz = liftA2 (-) lgpw jjzc
hqmp = liftA2 (-) dqgq qwlr
lfgf = pure 3
tjzh = pure 2
wqsn = liftA2 (*) zdcw vmjm
nhfw = liftA2 (*) pwtr dfzs
zrwd = pure 3
pjvn = liftA2 (+) nqpj twcs
ntnq = pure 7
qngl = liftA2 (+) tlpg rfbv
jmnq = liftA2 (+) zfbf nrzl
jjsp = pure 2
jpjc = liftA2 (-) tthn zvrs
msqr = liftA2 (*) nzjg zrvl
fshf = pure 2
jqhh = liftA2 (+) wlsr vjvh
ctwp = pure 2
nrvs = pure 2
cglc = pure 3
zsjb = pure 5
pbrt = liftA2 (+) fmbs cpcs
zmfh = liftA2 (+) mqbv dhht
glgt = liftA2 (+) hhqf njnt
pwvm = liftA2 (+) hwvg ncjj
vjcb = pure 3
vjmf = liftA2 (*) tcfq lnbv
wgrs = pure 2
vdbd = pure 2
gtfc = liftA2 (+) tjwc qcdj
htjn = liftA2 (*) ltft tllg
hqdl = liftA2 (-) swvg mcsc
rvss = pure 16
lqgq = pure 15
bccm = liftA2 (-) czgc gvgd
bwsq = liftA2 (-) rwdh cfrc
vrpd = pure 8
jjbs = pure 4
gslb = liftA2 (+) fbws rnwm
vshr = pure 2
mjzm = liftA2 (*) gzmq tlfd
grfl = pure 3
jqhc = pure 3
zvzw = pure 2
prdt = liftA2 (+) glhl hqvl
rslr = liftA2 (*) hsjv tdlm
rldn = liftA2 (*) vzjm jgls
vwmp = liftA2 (+) brns lczw
wjwc = pure 2
rgnv = pure 3
gggz = pure 6
bgzj = pure 5
qfmj = liftA2 (+) qmql jpmr
hfrz = pure 13
jjcq = pure 15
dbgl = pure 5
gmnc = pure 7
rgfh = liftA2 (*) lrpn htdr
gtrl = pure 17
fqms = pure 4
lvlm = pure 2
hqjf = liftA2 (*) tqfv jjpm
jdfv = liftA2 (*) gpff tstt
nsrm = pure 2
dphm = pure 3
fdbz = pure 3
stnh = liftA2 (*) hnfd fjrq
nnph = pure 13
lmcq = pure 8
zfcc = pure 20
tdrv = pure 7
ngml = pure 2
lzfr = liftA2 (*) cwzd fmwb
ghsz = liftA2 (*) zzvb mbts
svjq = liftA2 (*) mjst hnmn
tnrg = pure 6
hvpg = liftA2 (+) qdfs fvcn
dbqh = pure 2
mmgp = pure 2
qsfc = liftA2 (+) mzgg sjqq
hhqf = liftA2 (+) dnhd jbth
vfbf = liftA2 (-) thlv msff
qhrs = liftA2 (/) nhst zhfg
brfg = liftA2 (*) tqpw fhpw
tpgr = liftA2 (*) zvbt dtpf
jjbt = pure 2
dqbp = liftA2 (/) vjwh jjsp
scgw = pure 5
phzt = liftA2 (*) gbsw vrbp
mwdw = pure 2
ptls = pure 12
jrcb = pure 2
bgnn = liftA2 (*) htbv fshf
wnnf = liftA2 (-) bcpv zqcf
vnsp = liftA2 (+) qrhw gzbc
gbhr = liftA2 (*) nrld blmh
jfzc = pure 3
mplg = liftA2 (+) vpqm tcfl
tppn = pure 2
jtbp = liftA2 (-) nmhz bsqc
srcq = pure 3
pttl = liftA2 (*) rfzz dnvd
jttb = liftA2 (*) zqvt pcvc
fnrn = pure 6
vhpz = pure 7
npgp = liftA2 (*) nhqr rwfc
cnhh = pure 2
nlpl = pure 1
wjmt = liftA2 (*) vflg hmsc
brng = pure 3
mbts = liftA2 (+) lddp nzsq
qljl = liftA2 (+) vzbv mbjt
rhgt = liftA2 (*) mdwp vpvf
fwpn = pure 2
mdwp = pure 3
rvmp = pure 2
zqtb = pure 3
ncrs = pure 2
mmrf = liftA2 (+) dmzf rpqc
zspq = liftA2 (*) jzpf tpwt
dsfh = pure 3
mpgw = pure 5
btrt = liftA2 (-) tbvd prlg
jbfp = liftA2 (+) lmlt mvwj
hgsr = pure 3
rllj = pure 2
wqgg = liftA2 (+) hrqs rpgq
nrcl = liftA2 (+) slmj gvgp
hpsd = pure 3
qqwf = liftA2 (*) ncvt bpwc
tlsg = pure 5
hfcg = liftA2 (*) frpb jstj
wmwz = liftA2 (+) jdfc tmsb
bglw = liftA2 (+) mptj hhtm
tdvc = liftA2 (*) tjvl gglj
tcfl = liftA2 (*) wlnb fbnl
njnt = liftA2 (+) sqrh cjjr
fjvj = liftA2 (+) ldtq rvtm
jqqw = liftA2 (*) hnzz gplr
lmvt = liftA2 (+) zqjl wjmt
cggn = pure 3
gvgp = pure 11
gpff = pure 3
jngf = liftA2 (+) mnfg cfmg
jrgw = pure 4
qzmc = liftA2 (+) zhrh tdcr
dghz = pure 4
zhzb = liftA2 (+) fzlc btrj
mrhp = pure 7
jthc = liftA2 (+) dhbb zwwq
jgjd = pure 4
cgcn = liftA2 (+) fbmv lcvr
nnjb = pure 2
ttsv = pure 13
gdvg = pure 10
mmgs = pure 3
hbml = pure 4
jppn = pure 4
spzt = liftA2 (*) mswg qqhb
gbph = pure 5
cfgt = liftA2 (-) gfdw bfsf
hwvg = liftA2 (*) dcpd hqfv
bwhh = pure 5
lmgz = liftA2 (*) shdm vdvd
zhfg = pure 4
jsbq = pure 2
hdvc = liftA2 (*) dghz wbrc
vmgn = pure 5
ddjh = liftA2 (+) jqmz rzbs
vnfc = liftA2 (*) qftr wmwq
hddh = liftA2 (*) zfcc hjgj
tqlc = liftA2 (*) crmv sdlz
lrsg = liftA2 (-) jctj fwlf
qqhj = liftA2 (*) spcz ssvq
ftts = liftA2 (/) qvnj hgvp
hpqd = liftA2 (+) thpp hldm
cfwv = liftA2 (-) dqvm dgzv
tmtp = pure 6
rbvd = liftA2 (*) dzgh jqhc
bwpv = liftA2 (+) jcgd vssd
hzfj = liftA2 (*) wlch bjvp
hfgs = pure 2
rbhb = liftA2 (*) rvnn pmcp
gzgr = pure 3
ljfn = liftA2 (*) lmcr pjqj
gmbp = pure 3
cvnq = pure 2
ldnq = liftA2 (*) lcmt njdb
btbr = liftA2 (+) gtrl lwfm
qwvp = pure 4
zpfh = pure 3
tbhl = pure 2
vjmp = liftA2 (+) ndnp lbqs
mbmd = pure 5
hndr = pure 5
qtzz = pure 1
pftv = liftA2 (+) tsnb mljb
mjpf = liftA2 (*) gcww ctwp
srtz = pure 2
dnlg = liftA2 (+) nsgc lwjh
cccn = liftA2 (*) rdhq cfgt
vpjw = liftA2 (/) qvjs srtz
nrqq = liftA2 (+) ggtc tnrg
hrnv = pure 3
rjhr = pure 2
fqrr = pure 4
pdzc = liftA2 (*) rcwr vdbd
qvhf = pure 4
gwlt = pure 2
tmsb = liftA2 (*) fvdm wdwj
jthn = liftA2 (*) wgwv wzdj
sfqw = pure 2
vhzd = liftA2 (-) pgcb nrhb
vvmv = liftA2 (*) mfrl zbfl
vrvs = pure 2
tnvf = liftA2 (*) vzmq vjmb
rprp = liftA2 (*) znlm tvwz
vtzz = liftA2 (+) fwgr frtl
sdfm = pure 3
dghp = pure 7
qdpl = liftA2 (/) tdvc dcsb
hcvv = liftA2 (*) hcfd thvj
msdv = liftA2 (*) ntzz zpvw
spqb = liftA2 (*) dsdj sgnm
svzn = pure 2
sdlz = liftA2 (*) csjp cppm
zsrs = pure 2
dhpr = pure 5
mwnz = pure 5
gpfh = pure 9
rnwn = liftA2 (*) ndmn flld
mqcz = pure 15
jcgd = pure 1
pzdl = pure 4
dprw = liftA2 (+) wqsn ljsh
hhtm = liftA2 (*) mftq rhqg
trpm = pure 5
nwvr = pure 3
blsh = pure 4
vhcc = liftA2 (*) qzvd fdbd
nlsz = liftA2 (*) dvgv njfv
vgft = pure 20
mjzd = liftA2 (*) qnnz glhz
ppdj = pure 5
scrb = liftA2 (+) mtgn cnjg
jtnc = pure 20
rvjs = pure 3
qnlg = liftA2 (*) gcld ddgb
jftm = pure 2
sfss = liftA2 (/) ppwp qwdv
vqsp = liftA2 (+) gnfl gntr
mztz = pure 3
zvpl = liftA2 (+) qqwz pjsd
dbrv = pure 14
nzzq = pure 3
tfnn = pure 3
hjmt = pure 12
nrbv = pure 2
mqmv = liftA2 (+) sffq zqfw
wpmm = pure 5
wqns = pure 2
wlnb = pure 11
fsgd = pure 3
mbsv = liftA2 (+) dzvt wsmb
glhz = liftA2 (+) csjz fsvs
pdjp = liftA2 (-) ngvh wpfw
lrwv = pure 9
jrdq = pure 16
qhgn = pure 5
gqbq = liftA2 (-) bsvl grfl
cwtn = liftA2 (+) znfh tnjc
qhdp = pure 3
pmsr = liftA2 (+) pzfh hcdp
gbsl = liftA2 (*) sglg gpgm
rbfv = liftA2 (*) qdcm sgwj
jbth = liftA2 (*) msnl hdtm
rqbs = liftA2 (*) slbf mbmg
wjwd = liftA2 (*) vvmr wdcn
hbph = pure 2
zpbn = liftA2 (+) prdm tscq
ghwp = pure 2
swvg = liftA2 (+) cgnn mldp
vmhg = pure 18
hpcs = pure 2
frpb = pure 2
jhdc = liftA2 (+) jdcc vcbv
pqwf = liftA2 (/) pbnc ssbq
qvql = liftA2 (+) ltpp prvw
fcvq = pure 5
gqrj = pure 4
qmql = liftA2 (/) lgfn jjbs
hlvd = pure 4
sgcw = liftA2 (/) jtbp spfg
tqpw = pure 4
hsrq = liftA2 (+) npbs qcql
nljr = liftA2 (*) dqbp nttj
mvvj = pure 2
zdcw = liftA2 (+) fzzd jppv
gdgj = pure 5
zcwq = pure 5
jrtn = pure 2
dplt = pure 16
ccbp = liftA2 (+) httg lsgf
tsjf = pure 6
bgcs = pure 6
vgls = pure 19
rsgc = pure 2
vhhr = liftA2 (+) pwgf gggz
btnn = pure 3
rpgq = pure 4
dwhf = liftA2 (*) vhpz fhph
nqpj = pure 19
njsw = pure 5
czgc = liftA2 (+) hwcm hvgv
fsvs = liftA2 (*) jlbt tpsm
cjjr = pure 18
ddmt = pure 3
tntr = pure 2
bdlr = liftA2 (+) wpjd jqhh
zgfb = pure 2
fnwv = liftA2 (*) hghw zrtf
scjj = liftA2 (*) mlct ttsv
fflq = pure 2
nlqt = pure 4
hpnh = liftA2 (*) qvmf bbqf
qzct = pure 5
tbtc = pure 3
wfjz = liftA2 (*) ppjb ffjf
mzrm = liftA2 (*) plzr rwfm
hvbp = pure 7
fwhp = liftA2 (*) lfjw bqcz
wtlp = liftA2 (+) lmgz qwws
zgsm = pure 2
nvql = liftA2 (+) bbjh blsf
sqrh = pure 19
gvwh = pure 3
mtpf = liftA2 (-) mdgl svjq
gjdb = liftA2 (*) wqmg pgfv
sqtr = liftA2 (*) wdfp mgmr
zfnh = pure 2
bjbz = liftA2 (*) chmm dbqh
hglh = pure 5
bqcb = liftA2 (+) jczs pqfg
bvbt = liftA2 (*) rlfn zpbn
jqfj = liftA2 (*) zfdl vgls
tbvp = liftA2 (*) jfnt dwqf
wnfr = liftA2 (/) zzfj zfnh
ctvz = pure 8
lgsd = liftA2 (*) vgqb bzfd
pdtt = liftA2 (+) pzzm gzrg
tbsd = liftA2 (*) fzpt lbng
lhbs = liftA2 (*) lccj jzjb
rdhq = pure 2
rpnq = pure 3
jjsd = pure 2
jwtq = liftA2 (*) wwqm pwsb
rgpp = liftA2 (+) glpb rrgm
pnwt = pure 3
frhj = pure 5
fddr = pure 14
slwr = liftA2 (+) szcs nljr
lmbd = liftA2 (+) hvqw rftc
gqpf = liftA2 (+) ptls ljpg
srhg = liftA2 (*) cglc jmjw
nsgc = liftA2 (+) ltsn jbgd
lppw = pure 4
qvlq = liftA2 (-) qhrs hpnh
hgrg = pure 2
vjvh = liftA2 (*) bmfr blqg
dwnf = liftA2 (/) tmzr zthw
clzb = pure 5
pglz = liftA2 (*) zhdt gqhb
qdjf = liftA2 (*) hmhn mdmt
pdvb = liftA2 (+) vbgt bwjq
vqmg = liftA2 (*) jqcj fjtm
hnfd = liftA2 (+) dnrs vsrz
wqmg = pure 2
chtn = pure 1
ccpc = pure 4
qlwn = liftA2 (+) mnmq tgzr
ftjl = pure 2
fphs = pure 3
lhzq = liftA2 (+) ncrd jqhr
hhvv = liftA2 (+) zsbm jltf
mmzw = pure 15
hhsl = liftA2 (*) zrdq zlbn
pmpn = pure 7
dwlf = liftA2 (*) sszs dfpr
mqzh = liftA2 (*) mtrz mbmd
ndff = pure 4
jqhz = pure 20
dnfc = liftA2 (/) vnws ttbq
zdbn = liftA2 (+) wsdr zdsb
zqcf = pure 4
fbmv = pure 11
fsbz = pure 2
nnth = liftA2 (*) fscc wrst
bgwp = pure 4
nrpt = pure 7
hnwb = liftA2 (*) vbbs wlth
wcvw = liftA2 (+) djfb jrpc
gtpb = liftA2 (+) wzzh ddmt
zvsm = pure 11
hrmm = pure 3
qtfs = pure 5
fhmj = pure 12
tblh = liftA2 (+) vbng hhsl


root = liftA2 (-) zhfp hghd
humn = readTVarIO x

eval h = do
    atomically $ writeTVar x h
    root

-- a negative and b positive
go a b
    | abs (b - a) < 1/100 = do
        x <- eval mid
        pure $ (round a :: Integer, realToFrac x)
    | otherwise = do
        q <- eval mid
        if q > 0
           then go a mid
           else go mid b
    where
        mid = (a + b) / 2


main = do
    let a = 10
    let b = 10000000000000

    x <- eval a
    y <- eval b
    print =<< go b a


